apiVersion: v1
kind: Service
metadata:
  name: todoapp-service
spec:
  type: NodePort
  selector:
    app: todoapp
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30080
